### ISSUE TITLE
List videos, View video, Upload video (Static)

### ISSUE THREAD

**Issue by atoo** [BuildForSDGCohort2/Team-004-Frontend#10]
Add the following screens to the app:
- list videos (Guest/Student/Teacher)
- view video (Guest/Student/Teacher)
- upload video (Teacher)

As the respective API endpoint aren't yet available, the screen will use static data for now.

Respective wireframes to use as guidance are to be finalized. Will add them once available.

Respective API endpoints are documented here https://docs.google.com/document/d/1Yj2bqFhWKQj5pcH84dRO312KQz2WlcrZjyvBf2reB7Q

**Comment by gisely9** [comment]
looks good

**Comment by atoo** [comment]
API Integrated.
