### ISSUE TITLE
UI/UX:  Register, Login, Upload, View wireframes

### ISSUE THREAD

**Issue by atoo** [BuildForSDGCohort2/Team-004-Frontend#7]
Providing wireframes for the following screen, based on Material Design:
- Account registration: both Student and Teacher can create an account, with email/password pair
- Account login: Student and Teacher can login
- Upload video: Teacher can upload video.
- View video: This is a screen where a Guest, Student or Teacher watch a selected video.

**Comment by mpolobe** [comment]
Done

**Comment by atoo** [comment]
Please check my feedbacks on slack, there is still needed work.

**Comment by gisely9** [comment]
done

**Comment by atoo** [comment]
Thank you
