### ISSUE TITLE
Add Sign up and Sign in screens

### ISSUE THREAD

**Issue by atoo** [BuildForSDGCohort2/Team-004-Frontend#9]
Add the following screens to the app:
- sign up (Guest)
- sign in (Guest)

on succcessful sign up, the sign in should be trigger automatically with the provided user inputs.
on successful sign in, the app should save in local storage user information like id, role, access token, and direct to videos list screen.

Respective wireframes to use as guidance are to be finalized. Will add them once available.

Respective API endpoints are documented here https://docs.google.com/document/d/1Yj2bqFhWKQj5pcH84dRO312KQz2WlcrZjyvBf2reB7Q

**Comment by ucheuzor** [comment]
I have seen it . Thanks

**Comment by atoo** [comment]
@ucheuzor  Please check Screen 1 (Sign up) and Screen 3 (Sign in) here https://share.proto.io/R75VMF/

In Screen 1, user should either choose "I am a Student" or "I am a Teacher", not both

In Screen 3, there should not be "I am a Student" or "I am a Teacher" checkboxes, and we should just have one "Sign in" button (it was purely for the design flow).

**Comment by ucheuzor** [comment]
All right. Am on it now. I have been a bit occupied with assignments off late

**Comment by atoo** [comment]
@ucheuzor What's the status on this task? Everything is available on backend now https://docs.google.com/document/d/1Yj2bqFhWKQj5pcH84dRO312KQz2WlcrZjyvBf2reB7Q/edit

**Comment by atoo** [comment]
Done.
